enum Textdraws_Enum
{
	Text:textdraw_PLAYER_REP_BACK[2],
	Text:textdraw_LOAD_SCREEN[LOAD_SCREEN_TEXTDRAWS_SIZE],
	Text:textdraw_SERVER_TIME,
	Text:textdraw_GPS_MAP[4],
	Text:textdraw_SHOP[5],
	Text:textdraw_SHOP_ARTICLES_BOX[6],
	Text:textdraw_SHOP_ARTICLE_BOX,
	Text:textdraw_TERRITORY_BOX,
	Text:textdraw_SHOP_TUNING[5],
	Text:textdraw_HUD[HUD_TEXTDRAWS_SIZE],
	Text:textdraw_COMBAT_MODE
}
new Textdraws[Textdraws_Enum];